language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.3.gemfile
  - gemfiles/rails_5.1.1.gemfile
matrix:
  allow_failures:
    - rvm: 2.4.1
    - rvm: ruby-head
  exclude:
      gemfile: gemfiles/rails_5.0.3.gemfile
      gemfile: gemfiles/rails_5.1.1.gemfile
script:
  - bundle exec rake rubocop
  - bundle exec rspec
