language: ruby
rvm:
  - 1.9.3
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
matrix:
  allow_failures:
    - rvm: 2.4.1
    - rvm: ruby-head
    - rvm: 1.9.3
  exclude:
      gemfile: gemfiles/rails_5.0.3.gemfile
      gemfile: gemfiles/rails_5.1.1.gemfile
script:
  - bundle install --gemfile $BUNDLE_GEMFILE
  - bundle exec rspec
